version: '3.9'

services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sibdev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=db
  #      POSTGRES_PORT: 5432

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./sibdev:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#    environment:
#      - DEBUG=True
#      - DJANGO_SETTINGS_MODULE=config.settings

